// <auto-generated />
using System;
using JwtAuthentication.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JwtAuthentication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JwtAuthentication.Database.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Staff"
                        },
                        new
                        {
                            Id = 4,
                            Name = "User"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("JwtAuthentication.Database.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateOnly?>("BirthDay")
                        .HasColumnType("Date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hà Nội",
                            BirthDay = new DateOnly(1995, 5, 12),
                            FullName = "Nguyễn Văn An",
                            Password = "123456",
                            UserName = "nguyenvanan"
                        },
                        new
                        {
                            Id = 2,
                            Address = "TP Hồ Chí Minh",
                            BirthDay = new DateOnly(1997, 8, 20),
                            FullName = "Trần Thị Bình",
                            Password = "123456",
                            UserName = "tranthibinh"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Đà Nẵng",
                            BirthDay = new DateOnly(1993, 3, 15),
                            FullName = "Lê Văn Cường",
                            Password = "123456",
                            UserName = "levancuong"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Cần Thơ",
                            BirthDay = new DateOnly(1999, 11, 2),
                            FullName = "Phạm Thị Dung",
                            Password = "123456",
                            UserName = "phamthidung"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Hải Phòng",
                            BirthDay = new DateOnly(1990, 1, 25),
                            FullName = "Hoàng Văn Em",
                            Password = "123456",
                            UserName = "hoangvanem"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Nam Định",
                            BirthDay = new DateOnly(1996, 6, 30),
                            FullName = "Vũ Thị Hoa",
                            Password = "123456",
                            UserName = "vuthihoa"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Bình Dương",
                            BirthDay = new DateOnly(1994, 9, 18),
                            FullName = "Đặng Văn Khoa",
                            Password = "123456",
                            UserName = "dangvankhoa"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Nghệ An",
                            BirthDay = new DateOnly(2000, 12, 5),
                            FullName = "Bùi Thị Lan",
                            Password = "123456",
                            UserName = "buithilan"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Khánh Hòa",
                            BirthDay = new DateOnly(1992, 4, 10),
                            FullName = "Phan Văn Minh",
                            Password = "123456",
                            UserName = "phanvanminh"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Quảng Ninh",
                            BirthDay = new DateOnly(1998, 7, 22),
                            FullName = "Đỗ Thị Ngọc",
                            Password = "123456",
                            UserName = "dothingoc"
                        });
                });

            modelBuilder.Entity("JwtAuthentication.Database.Entities.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("JwtAuthentication.Database.Entities.AppUserRole", b =>
                {
                    b.HasOne("JwtAuthentication.Database.Entities.AppRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JwtAuthentication.Database.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JwtAuthentication.Database.Entities.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
